image: Visual Studio 2015

build_script:
- .\scripts\fetch.qt.5.11.1.msvc2015.bat


artifacts:
- path: qt.5.11.1.msvc2015.7z


deploy:
  provider: GitHub
  auth_token:
    secure: PiQDTyaNV3HdYRawTlwyD/bsMbpBg2Kx+/BEUEz9qOasvZlDBmxj3tFB0bNYwXIc
  artifact: qt.5.11.1.msvc2015.7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
