image: Visual Studio 2015

build_script:
- .\scripts\fetch.boost.1.67.0.bat


artifacts:
- path: boost.1.67.0.7z


deploy:
  provider: GitHub
  auth_token:
    secure: PiQDTyaNV3HdYRawTlwyD/bsMbpBg2Kx+/BEUEz9qOasvZlDBmxj3tFB0bNYwXIc
  artifact: boost.1.67.0.7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
