image: Visual Studio 2015

init:
  - ps: (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -like 'ethernet*'}).IPAddress

build_script:
- .\scripts\fetch.boost.1.67.0.bat
- .\scripts\fetch.qt.5.11.1.msvc2015.bat


artifacts:
- path: qt.5.11.1.msvc2015.7z
- path: boost.1.67.0.7z